import type { Metadata } from "next";
import { Pridi,  Mitr} from "next/font/google";
import "../globals.css";

const pridi = Pridi({
    variable: "--font-pridi",
    subsets: ["thai"],
    weight: "400"
})

const mitr = Mitr({
    variable: "--font-mitr",
    subsets: ["latin"],
    weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pridi.variable} ${mitr.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
